"""vault_wiki.py — community-based wiki generation over the vault graph.

For each detected community in ``.charon/graph-communities.json``, writes a
summary markdown doc under ``07-References/communities/community-NN.md``.
The doc enumerates the community's nodes, top connections, and (if an
Anthropic key is available) an LLM-authored paragraph naming the theme
the community appears to represent.

Why "borrow from graphify": graphify's wiki mode auto-generates one
article per detected community. That's the moment a vault stops being a
passive store and starts surfacing themes you'd otherwise have to
manually curate. For a large vault — many org units, hundreds of people,
hundreds of captures — auto-summary of community clusters is the single
biggest synthesis-time-saver on the borrows list.

Modes:

- ``generate`` — write/update community docs (calls LLM if available)
- ``plan``     — dry-run: list which communities would be written, no LLM
- ``stats``    — show summary of what was last written

Cost note: ``generate`` calls Anthropic Haiku once per community.
Typical: $0.01-0.05 per community. A vault with 12 communities is
roughly $0.12-0.60 per full run. ``plan`` is free.

Idempotency: communities are keyed by their stable Louvain community-ID
+ node-set hash. Already-written docs are SKIPPED unless ``--force``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.communities import (  # noqa: E402
    communities_path,
    read_communities,
)
from lib.harness_paths import vault_root  # noqa: E402


WIKI_DIR_REL = "07-References/communities"
MAX_NODES_IN_PROMPT = 40   # cap for token budget
DEFAULT_MAX_COMMUNITIES = 30   # don't blow LLM budget on huge graphs


def wiki_dir() -> Path:
    return vault_root() / WIKI_DIR_REL


# ---------- Hashing for idempotency ----------

def _community_signature(nodes: List[str]) -> str:
    """Stable signature of a community: hash of its sorted node-list."""
    serialised = "\n".join(sorted(nodes))
    return hashlib.sha256(serialised.encode("utf-8")).hexdigest()[:16]


def _signature_in_file(path: Path) -> Optional[str]:
    """Read the community-signature frontmatter field from an existing doc."""
    if not path.exists():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    m = re.search(r"^community_signature:\s*([0-9a-f]+)\s*$", text, re.MULTILINE)
    return m.group(1) if m else None


# ---------- Doc rendering ----------

def _doc_filename(community_id: int) -> str:
    return f"community-{community_id:02d}.md"


def _render_community_doc(
    community_id: int,
    nodes: List[str],
    summary: str,
    signature: str,
    llm_status: str,
) -> str:
    """Render the full markdown doc for one community."""
    now = time.strftime("%Y-%m-%d")
    sample_nodes = nodes[:25]
    tail = f"\n_... and {len(nodes) - 25} more nodes._" if len(nodes) > 25 else ""
    sample_list = "\n".join(f"- `{n}`" for n in sample_nodes)

    return f"""---
type: vault-community
generated_at: {now}
community_id: {community_id}
node_count: {len(nodes)}
community_signature: {signature}
llm_status: {llm_status}
source: scripts/vault_wiki.py
---

# Community {community_id:02d}

## Theme summary

{summary}

## Nodes ({len(nodes)})

{sample_list}{tail}

## Provenance

This document was auto-generated by `scripts/vault_wiki.py` from the
community detection results in `.charon/graph-communities.json`. The
`community_signature` field above is a hash of the node-list — if the
community membership changes upstream, the next `vault_wiki.py generate`
run will detect the drift and rewrite this doc.

To regenerate manually: `python scripts/vault_wiki.py generate --force`.
"""


# ---------- LLM summary (optional) ----------

def _llm_summarise(nodes: List[str], community_id: int) -> Tuple[Optional[str], str]:
    """Call Anthropic Haiku to summarise the community. Returns (summary, status).

    status: "ok" / "key-missing" / "anthropic-import-failed" / "api-error: ..."
    """
    try:
        import anthropic  # type: ignore
    except ImportError:
        return None, "anthropic-import-failed"

    # Read API key from the standard Charon secrets path
    import os
    home = os.path.expanduser("~")
    key_path = Path(home) / ".secrets" / "anthropic.json"
    api_key = None
    if key_path.exists():
        try:
            data = json.loads(key_path.read_text(encoding="utf-8"))
            api_key = data.get("api_key")
        except (json.JSONDecodeError, OSError):
            pass
    if not api_key:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return None, "key-missing"

    sample = nodes[:MAX_NODES_IN_PROMPT]
    prompt = (
        "You are summarising a community of related entities detected in a personal "
        "knowledge graph (people, projects, concepts, documents). Write a 2-3 sentence "
        "paragraph naming the theme this community represents — what they have in common, "
        "what activity / topic they revolve around. Be concrete; don't generalise. If the "
        "names don't suggest a coherent theme, say so honestly.\n\n"
        f"Community {community_id} contains {len(nodes)} entities. Sample:\n"
        + "\n".join(f"- {n}" for n in sample)
        + ("\n... and more." if len(nodes) > MAX_NODES_IN_PROMPT else "")
    )

    try:
        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        text = resp.content[0].text if resp.content else ""
        return text.strip(), "ok"
    except Exception as exc:
        return None, f"api-error: {type(exc).__name__}"


def _placeholder_summary(nodes: List[str], reason: str) -> str:
    """When LLM is unavailable, write a structural summary so the doc is still useful."""
    sample = ", ".join(f"`{n}`" for n in nodes[:8])
    more = f" (+{len(nodes) - 8} more)" if len(nodes) > 8 else ""
    return (
        f"*Auto-summary unavailable ({reason}).*\n\n"
        f"This community has **{len(nodes)} entities** including {sample}{more}. "
        f"Run `scripts/vault_wiki.py generate --force` once an Anthropic API key is "
        f"configured to produce a theme summary."
    )


# ---------- Generation flow ----------

def generate_wiki_docs(
    use_llm: bool = True,
    force: bool = False,
    max_communities: int = DEFAULT_MAX_COMMUNITIES,
    min_community_size: int = 2,
) -> dict:
    """Generate / update community wiki docs. Returns a result summary."""
    data = read_communities()
    if not data:
        return {"ok": False, "reason": f"no communities file at {communities_path()} — run `python scripts/cluster_vault.py` first"}

    communities = data.get("communities", {})
    if not communities:
        return {"ok": False, "reason": "communities file has no communities entry"}

    out_dir = wiki_dir()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Sort by size descending, cap at max_communities
    ordered = sorted(
        ((int(cid), c) for cid, c in communities.items() if c["size"] >= min_community_size),
        key=lambda kv: -kv[1]["size"],
    )[:max_communities]

    written: List[dict] = []
    skipped: List[dict] = []
    for community_id, c in ordered:
        nodes = c["nodes"]
        signature = _community_signature(nodes)
        path = out_dir / _doc_filename(community_id)

        if not force and _signature_in_file(path) == signature:
            skipped.append({"community_id": community_id, "size": len(nodes), "reason": "unchanged"})
            continue

        if use_llm:
            summary, llm_status = _llm_summarise(nodes, community_id)
            if not summary:
                summary = _placeholder_summary(nodes, llm_status)
        else:
            summary = _placeholder_summary(nodes, "dry-run / use_llm=False")
            llm_status = "skipped"

        doc = _render_community_doc(
            community_id=community_id,
            nodes=nodes,
            summary=summary,
            signature=signature,
            llm_status=llm_status,
        )
        path.write_text(doc, encoding="utf-8")
        written.append({"community_id": community_id, "size": len(nodes), "path": str(path), "llm_status": llm_status})

    return {
        "ok": True,
        "written": written,
        "skipped": skipped,
        "out_dir": str(out_dir),
    }


def plan_wiki_docs(max_communities: int = DEFAULT_MAX_COMMUNITIES, min_community_size: int = 2) -> dict:
    """Show what would be written without calling the LLM."""
    return generate_wiki_docs(use_llm=False, force=False, max_communities=max_communities, min_community_size=min_community_size)


# ---------- CLI ----------

def _configure_stdio_for_unicode() -> None:
    if sys.platform.startswith("win"):
        for stream in (sys.stdout, sys.stderr):
            try:
                stream.reconfigure(encoding="utf-8")
            except Exception:
                pass


def main() -> int:
    _configure_stdio_for_unicode()
    parser = argparse.ArgumentParser(description="Generate per-community summary docs from the vault graph")
    sub = parser.add_subparsers(dest="command", required=True)

    p_gen = sub.add_parser("generate", help="Write / update community docs (uses Anthropic if key available)")
    p_gen.add_argument("--force", action="store_true", help="Rewrite even when signature unchanged")
    p_gen.add_argument("--max", type=int, default=DEFAULT_MAX_COMMUNITIES, help="Cap on number of communities to write")
    p_gen.add_argument("--min-size", type=int, default=2, help="Skip communities smaller than this")
    p_gen.add_argument("--no-llm", action="store_true", help="Skip LLM call; write placeholder summaries")

    p_plan = sub.add_parser("plan", help="Dry-run: list which communities would be written, no LLM cost")
    p_plan.add_argument("--max", type=int, default=DEFAULT_MAX_COMMUNITIES)
    p_plan.add_argument("--min-size", type=int, default=2)

    p_stats = sub.add_parser("stats", help="Show what's already in 07-References/communities/")
    p_stats.set_defaults(command="stats")

    args = parser.parse_args()

    if args.command == "stats":
        out_dir = wiki_dir()
        if not out_dir.exists():
            print(f"no community docs at {out_dir}")
            return 1
        docs = sorted(out_dir.glob("community-*.md"))
        print(f"{len(docs)} community doc(s) at {out_dir}")
        for d in docs[:20]:
            sig = _signature_in_file(d) or "(no signature)"
            print(f"  {d.name}  sig={sig}")
        if len(docs) > 20:
            print(f"  ... +{len(docs) - 20} more")
        return 0

    if args.command == "plan":
        result = plan_wiki_docs(max_communities=args.max, min_community_size=args.min_size)
        if not result["ok"]:
            sys.stderr.write(f"{result['reason']}\n")
            return 1
        print(f"PLAN — would write {len(result['written'])} doc(s) to {result['out_dir']}")
        for w in result["written"]:
            print(f"  community-{w['community_id']:02d}  size={w['size']}  → {w['path']}")
        return 0

    if args.command == "generate":
        result = generate_wiki_docs(
            use_llm=not args.no_llm,
            force=args.force,
            max_communities=args.max,
            min_community_size=args.min_size,
        )
        if not result["ok"]:
            sys.stderr.write(f"{result['reason']}\n")
            return 1
        print(f"wrote {len(result['written'])} doc(s) (skipped {len(result['skipped'])} unchanged) → {result['out_dir']}")
        for w in result["written"]:
            print(f"  community-{w['community_id']:02d}  size={w['size']}  llm={w['llm_status']}")
        return 0

    return 2


if __name__ == "__main__":
    sys.exit(main())
